a=5.7
b=2
c=a+b
print("%s + %s = %s" %(a,b,c))
c=a-b
print("%s - %s = %s" %(a,b,c))
c=a*b
print("%s * %s = %s" %(a,b,c))
c=a/b
print("%s / %s = %s" %(a,b,c))
c=a%b
print("%s  %s = %s" %(a,b,c))
c=a**b
print("%s ** %s = %s" %(a,b,c))
c=a//b
print("%s // %s = %s" %(a,b,c))
